version: '3.8'
services:
  db:
    image: postgres:15.1-alpine
    restart: always
    environment:
      # Note: This is only a placeholder
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    ports:
      - '5432:5432'
    volumes:
      - 'db:/var/lib/postgresql/data'
  adminer:
    image: adminer:4.8.1
    restart: always
    ports:
      - 9090:8080
volumes:
  db:
    driver: local
